### ISSUE TITLE
Provider SSH Public Key not displayed

### ISSUE THREAD

**Issue by pyotr777** [pyotr777/kportal#3]
![screen shot 2016-09-07 at 17 19 00](https://cloud.githubusercontent.com/assets/485462/18304757/2facc3e8-751f-11e6-8938-a208e43d8c66.png)

**Comment by tuannp** [comment]
Bugfixed[https://github.com/pyotr777/kportal/commit/5c42c3b439193860ea839a47ec19813af49227a3](url)

**Comment by pyotr777** [comment]
User need to relogin to K-portal to see the key?

**Comment by pyotr777** [comment]
Fixed.
